name: Daily PostHog Sync

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.18
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Compile application
        run: mix compile

      - name: Run traffic sync
        run: mix sync
        env:
          GPS_GITHUB_ID: ${{ secrets.GPS_GITHUB_ID }}
          GPS_GITHUB_KEY: ${{ secrets.GPS_GITHUB_KEY }}
          GPS_GITHUB_URL: ${{ secrets.GPS_GITHUB_URL }}
          GPS_POSTHOG_PHC: ${{ secrets.GPS_POSTHOG_PHC }}
          GPS_POSTHOG_PHX: ${{ secrets.GPS_POSTHOG_PHX }}
          GPS_POSTHOG_URL: ${{ secrets.GPS_POSTHOG_URL }}
          GPS_ALLOW_FORKS: ${{ secrets.GPS_ALLOW_FORKS }}
          GPS_ALLOW_PRIVATE: ${{ secrets.GPS_ALLOW_PRIVATE }}
          GPS_ALLOW_ARCHIVED: ${{ secrets.GPS_ALLOW_ARCHIVED }}
